# Netlify Configuration for XAI Platform Frontend
[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"  # Netlify Next.js plugin handles this automatically

[build.environment]
  NODE_VERSION = "20"  # Updated to Node 20 for Next.js 15 compatibility

# Next.js specific configuration - handles SSR and routing automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Proxy API requests to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://xaiplatformmasterthesis-production.up.railway.app/api/:splat"
  status = 200
  force = true
