# Netlify Configuration for XAI Platform Frontend
[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js specific configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Proxy API requests to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://xaiplatformmasterthesis-production.up.railway.app/api/:splat"
  status = 200
  force = true
